# Generated by Django 4.2.16 on 2025-01-06 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('author_id', models.AutoField(primary_key=True, serialize=False)),
                ('author_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'authors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=45)),
                ('published_year', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'books',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fines',
            fields=[
                ('fine_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=4)),
                ('issued_date', models.DateField()),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'fines',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('genre_id', models.AutoField(primary_key=True, serialize=False)),
                ('genre_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'genres',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Holds',
            fields=[
                ('hold_id', models.AutoField(primary_key=True, serialize=False)),
                ('hold_date', models.DateField()),
                ('release_date', models.DateField()),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'holds',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('loan_date', models.DateField()),
                ('return_date', models.DateField()),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'loans',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notifictions',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=255)),
                ('sent_date', models.DateField()),
                ('notification_read', models.IntegerField()),
                ('notifiction_type', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'notifictions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhysicalBooks',
            fields=[
                ('physical_book_id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.IntegerField()),
            ],
            options={
                'db_table': 'physical_books',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=5)),
                ('password_hash', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Booksauthors',
            fields=[
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='libraryapp.books')),
            ],
            options={
                'db_table': 'booksauthors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Booksgenres',
            fields=[
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='libraryapp.books')),
            ],
            options={
                'db_table': 'booksgenres',
                'managed': False,
            },
        ),
    ]
