# Generated by Django 4.2.16 on 2025-01-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0003_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryappContact',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=254)),
                ('address', models.TextField()),
                ('working_hours', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'libraryapp_contact',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LibraryappFaq',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
            ],
            options={
                'db_table': 'libraryapp_faq',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='books',
            options={'managed': True},
        ),
    ]
